"""Add Veriff KYC fields

Revision ID: 20dce5deb826
Revises: 119d89ab6a65
Create Date: 2025-12-17 15:34:16.355479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20dce5deb826'
down_revision: Union[str, None] = '119d89ab6a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('veriff_session_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('veriff_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('kyc_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('kyc_skipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_skipped')
    op.drop_column('users', 'kyc_verified_at')
    op.drop_column('users', 'veriff_status')
    op.drop_column('users', 'veriff_session_id')
    # ### end Alembic commands ###
