"""Add provider to transactions

Revision ID: 32754fd2da9d
Revises: e46679ae23ee
Create Date: 2025-12-10 15:27:42.442426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32754fd2da9d'
down_revision: Union[str, None] = 'e46679ae23ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bank_accounts', 'users', ['user_id'], ['id'])
    op.alter_column('reports', 'type',
               existing_type=postgresql.ENUM('IVA', 'IRPF', name='reporttype'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PAID', name='reportstatus'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('provider', sa.String(length=20), nullable=True))
    op.alter_column('transactions', 'type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype'),
               existing_nullable=True)
    op.drop_column('transactions', 'provider')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PAID', name='reportstatus'),
               existing_nullable=True)
    op.alter_column('reports', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('IVA', 'IRPF', name='reporttype'),
               existing_nullable=True)
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    # ### end Alembic commands ###
