"""Add is_removed column to reminders table

Revision ID: 90b7c109dbe3
Revises: 697237cb781f
Create Date: 2026-01-02 20:10:47.176798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90b7c109dbe3'
down_revision: Union[str, None] = '697237cb781f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - manually edited ###
    
    # Add columns with server defaults for existing rows
    op.add_column('invoices', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    op.add_column('reminders', sa.Column('is_removed', sa.Boolean(), nullable=False, server_default='false'))
    
    op.add_column('transactions', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Handle reports table changes
    op.alter_column('reports', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('reports', 'report_type', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('reports', 'period', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('reports', 'deadline', existing_type=sa.DATE(), nullable=False)
    
    # Drop index and columns from reports
    op.drop_index('ix_reports_period', table_name='reports')
    op.drop_column('reports', 'tracking_id')
    op.drop_column('reports', 'explain_metadata')
    op.drop_column('reports', 'pdf_path')
    op.drop_column('reports', 'type')
    op.drop_column('reports', 'owed_amount')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'deleted_at')
    op.drop_column('transactions', 'is_deleted')
    op.add_column('reports', sa.Column('owed_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('pdf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('explain_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('tracking_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_reports_period'), 'reports', ['period'], unique=False)
    op.alter_column('reports', 'deadline',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('reports', 'period',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reminders', 'is_removed')
    op.drop_column('invoices', 'deleted_at')
    op.drop_column('invoices', 'is_deleted')
    # ### end Alembic commands ###
