"""Add city and business_address to users

Revision ID: 0931b3333a79
Revises: fdeb1bf91fae
Create Date: 2025-12-31 17:34:48.265120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0931b3333a79'
down_revision: Union[str, None] = 'fdeb1bf91fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_address', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'business_address')
    # ### end Alembic commands ###
