"""Add Plaid integration fields

Revision ID: 119d89ab6a65
Revises: a1b0b0c4cde6
Create Date: 2025-12-17 10:29:55.350738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119d89ab6a65'
down_revision: Union[str, None] = 'a1b0b0c4cde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('account_name', sa.String(length=100), nullable=True))
    op.add_column('bank_accounts', sa.Column('account_mask', sa.String(length=10), nullable=True))
    op.add_column('bank_accounts', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('bank_accounts', sa.Column('plaid_account_id', sa.String(length=100), nullable=True))
    op.add_column('bank_accounts', sa.Column('plaid_item_id', sa.String(length=100), nullable=True))
    op.add_column('bank_accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('bank_accounts', 'bank_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_bank_accounts_plaid_account_id'), 'bank_accounts', ['plaid_account_id'], unique=False)
    op.add_column('transactions', sa.Column('plaid_transaction_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_transactions_plaid_transaction_id'), 'transactions', ['plaid_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_plaid_transaction_id'), table_name='transactions')
    op.drop_column('transactions', 'plaid_transaction_id')
    op.drop_index(op.f('ix_bank_accounts_plaid_account_id'), table_name='bank_accounts')
    op.alter_column('bank_accounts', 'bank_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('bank_accounts', 'created_at')
    op.drop_column('bank_accounts', 'plaid_item_id')
    op.drop_column('bank_accounts', 'plaid_account_id')
    op.drop_column('bank_accounts', 'account_type')
    op.drop_column('bank_accounts', 'account_mask')
    op.drop_column('bank_accounts', 'account_name')
    # ### end Alembic commands ###
