"""add_is_removed_to_reminders

Revision ID: 16f45593f315
Revises: 0931b3333a79
Create Date: 2026-01-02 10:47:55.182649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f45593f315'
down_revision: Union[str, None] = '0931b3333a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('is_removed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'is_removed')
    # ### end Alembic commands ###
