"""add_verifactu_reports_tables

Revision ID: 35ee00f3007a
Revises: 3cc4b609d4ac
Create Date: 2026-01-02 18:35:19.167392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35ee00f3007a'
down_revision: Union[str, None] = '3cc4b609d4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_column('invoices', 'deleted_at')
    op.drop_column('invoices', 'is_deleted')
    op.drop_column('reminders', 'is_removed')
    op.add_column('reports', sa.Column('report_type', sa.String(length=50), nullable=True))
    op.add_column('reports', sa.Column('modelo', sa.String(length=10), nullable=True))
    op.add_column('reports', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('reports', sa.Column('submit_date', sa.Date(), nullable=True))
    op.add_column('reports', sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('reports', sa.Column('calculation_data', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('verifactu_hash', sa.String(length=64), nullable=True))
    op.add_column('reports', sa.Column('verifactu_mode', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('xml_submission', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('csv_code', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('submitted_by_ip', sa.String(length=45), nullable=True))
    op.drop_index(op.f('ix_transactions_is_deleted'), table_name='transactions')
    op.drop_column('transactions', 'is_deleted')
    op.drop_column('transactions', 'deleted_at')
    op.add_column('users', sa.Column('nif', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('registration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'nif')
    op.add_column('transactions', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_transactions_is_deleted'), 'transactions', ['is_deleted'], unique=False)
    op.drop_column('reports', 'submitted_by_ip')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'csv_code')
    op.drop_column('reports', 'xml_submission')
    op.drop_column('reports', 'verifactu_mode')
    op.drop_column('reports', 'verifactu_hash')
    op.drop_column('reports', 'calculation_data')
    op.drop_column('reports', 'total_tax')
    op.drop_column('reports', 'submit_date')
    op.drop_column('reports', 'deadline')
    op.drop_column('reports', 'modelo')
    op.drop_column('reports', 'report_type')
    op.add_column('reminders', sa.Column('is_removed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
