"""add_aeat_feilds_to_report_and_invoice

Revision ID: 5ad4b1c430ec
Revises: c7098916ec26
Create Date: 2026-01-08 20:36:37.652918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad4b1c430ec'
down_revision: Union[str, None] = 'c7098916ec26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('aeat_submitted_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('aeat_environment', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('aeat_submitted_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('aeat_environment', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'aeat_environment')
    op.drop_column('reports', 'aeat_submitted_at')
    op.drop_column('invoices', 'aeat_environment')
    op.drop_column('invoices', 'aeat_submitted_at')
    # ### end Alembic commands ###
