"""Add full models for users, banks, transactions, reports

Revision ID: 68bbd8a0c0b0
Revises: 06bfebe60c74
Create Date: 2025-12-08 21:44:10.990761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68bbd8a0c0b0'
down_revision: Union[str, None] = '06bfebe60c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='familystatus'), nullable=True))
    op.add_column('users', sa.Column('num_children', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('nie_dni', postgresql.BYTEA(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_region'), 'users', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_region'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'nie_dni')
    op.drop_column('users', 'region')
    op.drop_column('users', 'num_children')
    op.drop_column('users', 'family_status')
    # ### end Alembic commands ###
