"""Add nie_dni and verified_kyc to users

Revision ID: a1857605291b
Revises: f14b415d6fce
Create Date: 2025-12-12 20:36:09.960551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1857605291b'
down_revision: Union[str, None] = 'f14b415d6fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_kyc', sa.Boolean(), nullable=True))
    op.alter_column('users', 'nie_dni',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nie_dni',
               existing_type=sa.String(length=20),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_column('users', 'verified_kyc')
    # ### end Alembic commands ###
