"""add_verifactu_chain_records_table

Revision ID: c1136822551d
Revises: 5ad4b1c430ec
Create Date: 2026-01-08 22:54:07.679689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1136822551d'
down_revision: Union[str, None] = '5ad4b1c430ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifactu_chain_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nif', sa.String(length=15), nullable=False),
    sa.Column('software_id', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_type', sa.String(length=10), nullable=False),
    sa.Column('hash_value', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('hash_input', sa.Text(), nullable=True),
    sa.Column('csv_code', sa.String(length=30), nullable=True),
    sa.Column('aeat_accepted', sa.Boolean(), nullable=True),
    sa.Column('aeat_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('aeat_environment', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifactu_chain_records_created_at'), 'verifactu_chain_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_verifactu_chain_records_hash_value'), 'verifactu_chain_records', ['hash_value'], unique=False)
    op.create_index(op.f('ix_verifactu_chain_records_id'), 'verifactu_chain_records', ['id'], unique=False)
    op.create_index(op.f('ix_verifactu_chain_records_invoice_id'), 'verifactu_chain_records', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_verifactu_chain_records_nif'), 'verifactu_chain_records', ['nif'], unique=False)
    op.create_index(op.f('ix_verifactu_chain_records_software_id'), 'verifactu_chain_records', ['software_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifactu_chain_records_software_id'), table_name='verifactu_chain_records')
    op.drop_index(op.f('ix_verifactu_chain_records_nif'), table_name='verifactu_chain_records')
    op.drop_index(op.f('ix_verifactu_chain_records_invoice_id'), table_name='verifactu_chain_records')
    op.drop_index(op.f('ix_verifactu_chain_records_id'), table_name='verifactu_chain_records')
    op.drop_index(op.f('ix_verifactu_chain_records_hash_value'), table_name='verifactu_chain_records')
    op.drop_index(op.f('ix_verifactu_chain_records_created_at'), table_name='verifactu_chain_records')
    op.drop_table('verifactu_chain_records')
    # ### end Alembic commands ###
