"""add_verifactu_events_relationships_and_indexes

Revision ID: c366d106bef9
Revises: 5cad5894ddd2
Create Date: 2026-01-08 18:48:15.323187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c366d106bef9'
down_revision: Union[str, None] = '5cad5894ddd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_verifactu_events_created_at'), table_name='invoice_verifactu_events')
    op.drop_index(op.f('ix_invoice_verifactu_events_event_type'), table_name='invoice_verifactu_events')
    op.alter_column('reminders', 'is_removed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_verifactu_events_created_at'), 'verifactu_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_verifactu_events_report_id'), 'verifactu_events', ['report_id'], unique=False)
    op.create_index(op.f('ix_verifactu_events_user_id'), 'verifactu_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifactu_events_user_id'), table_name='verifactu_events')
    op.drop_index(op.f('ix_verifactu_events_report_id'), table_name='verifactu_events')
    op.drop_index(op.f('ix_verifactu_events_created_at'), table_name='verifactu_events')
    op.alter_column('reminders', 'is_removed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_invoice_verifactu_events_event_type'), 'invoice_verifactu_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_invoice_verifactu_events_created_at'), 'invoice_verifactu_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
