"""add_certificate_storage.py

Revision ID: c7098916ec26
Revises: c366d106bef9
Create Date: 2026-01-08 20:18:20.162095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7098916ec26'
down_revision: Union[str, None] = 'c366d106bef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeat_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submission_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('xml_sent', sa.Text(), nullable=True),
    sa.Column('xml_hash', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('csv_code', sa.String(length=50), nullable=True),
    sa.Column('response_code', sa.String(length=20), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('error_codes', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('certificate_fingerprint', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeat_submissions_id'), 'aeat_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_aeat_submissions_submitted_at'), 'aeat_submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_aeat_submissions_user_id'), 'aeat_submissions', ['user_id'], unique=False)
    op.create_table('user_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('subject_cn', sa.String(length=255), nullable=True),
    sa.Column('subject_nif', sa.String(length=20), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('certificate_data_encrypted', postgresql.BYTEA(), nullable=False),
    sa.Column('password_encrypted', postgresql.BYTEA(), nullable=False),
    sa.Column('encryption_salt', postgresql.BYTEA(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificates_fingerprint'), 'user_certificates', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_user_certificates_id'), 'user_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_user_certificates_user_id'), 'user_certificates', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_certificates_user_id'), table_name='user_certificates')
    op.drop_index(op.f('ix_user_certificates_id'), table_name='user_certificates')
    op.drop_index(op.f('ix_user_certificates_fingerprint'), table_name='user_certificates')
    op.drop_table('user_certificates')
    op.drop_index(op.f('ix_aeat_submissions_user_id'), table_name='aeat_submissions')
    op.drop_index(op.f('ix_aeat_submissions_submitted_at'), table_name='aeat_submissions')
    op.drop_index(op.f('ix_aeat_submissions_id'), table_name='aeat_submissions')
    op.drop_table('aeat_submissions')
    # ### end Alembic commands ###
