"""Fix family_status enum to lowercase

Revision ID: e46679ae23ee
Revises: 68bbd8a0c0b0
Create Date: 2025-12-08 22:03:56.302628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46679ae23ee'
down_revision: Union[str, None] = '68bbd8a0c0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bank_accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    # ### end Alembic commands ###
